global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'image-processor'
    static_configs:
      - targets: ['host.docker.internal:8080']  # Usa el nombre del servicio y puerto

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']